name: honey
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0" 

#========================================

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_database: ^11.3.4
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5 # Firestore for database
  shared_preferences: ^2.5.2 # For storing login status

  # UI and utility dependencies
  fluttertoast: ^8.2.12 # For showing toast messages
  # qr_code_scanner: ^1.0.1 # For QR code scanning
  google_fonts: ^6.2.1 # Optional: For custom fonts
  provider: ^6.1.2 # Optional: For state management
  firebase_auth_web: ^5.14.1
  firebase_core_web: ^2.12.1
  google_sign_in: ^6.3.0
  weatherapi: ^1.1.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # For linting and code quality

flutter:
  uses-material-design: true


  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # Optional: Add custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700