// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDamRHkaqaWbTY-RC1VOknZaz4VZ3jjHrc',
    appId: '1:828554584899:web:8c126ae6f133c1abaa45f6',
    messagingSenderId: '828554584899',
    projectId: 'courseproject-1ae7d',
    authDomain: 'courseproject-1ae7d.firebaseapp.com',
    databaseURL: 'https://courseproject-1ae7d-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-1ae7d.firebasestorage.app',
    measurementId: 'G-H9DJYJW31R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7bZgiiNqPRqsyHg9k6sGesmwEdkGQDiQ',
    appId: '1:828554584899:android:84bfc99352d13b04aa45f6',
    messagingSenderId: '828554584899',
    projectId: 'courseproject-1ae7d',
    databaseURL: 'https://courseproject-1ae7d-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-1ae7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABa85Bk3WSdCycq5XqWudnJMLEe_aXrsQ',
    appId: '1:828554584899:ios:9eb5d8cc3a53dcd4aa45f6',
    messagingSenderId: '828554584899',
    projectId: 'courseproject-1ae7d',
    databaseURL: 'https://courseproject-1ae7d-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-1ae7d.firebasestorage.app',
    iosClientId: '828554584899-aocb393524fjonjapi90j7d4n15k83bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.honey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABa85Bk3WSdCycq5XqWudnJMLEe_aXrsQ',
    appId: '1:828554584899:ios:9eb5d8cc3a53dcd4aa45f6',
    messagingSenderId: '828554584899',
    projectId: 'courseproject-1ae7d',
    databaseURL: 'https://courseproject-1ae7d-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-1ae7d.firebasestorage.app',
    iosClientId: '828554584899-aocb393524fjonjapi90j7d4n15k83bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.honey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDamRHkaqaWbTY-RC1VOknZaz4VZ3jjHrc',
    appId: '1:828554584899:web:9e0c41f951fee744aa45f6',
    messagingSenderId: '828554584899',
    projectId: 'courseproject-1ae7d',
    authDomain: 'courseproject-1ae7d.firebaseapp.com',
    databaseURL: 'https://courseproject-1ae7d-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-1ae7d.firebasestorage.app',
    measurementId: 'G-1MKRPPD1BH',
  );
}
